spring:
  application:
    name: swift
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  threads:
    virtual:
      enabled: true
